# Generated by Django 5.1.1 on 2024-09-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.BigIntegerField(null=True)),
                ('image', models.CharField()),
                ('release_date', models.DateField(null=True)),
                ('lte_exists', models.BooleanField()),
                ('slug', models.SlugField(editable=False)),
            ],
        ),
    ]
